const SUPABASE_URL='https://xhmsydvbmrizcbvhdjyq.supabase.co';
const SUPABASE_KEY='sb_publishable_ZZTfBI94AtOC6RsGNuMXYA_FemjbVk9';
const list=document.querySelector('#list'),search=document.querySelector('#search'),count=document.querySelector('#count'),empty=document.querySelector('#empty');
const tabs=document.querySelector('#category-tabs'),categoryTitle=document.querySelector('#category-title'),categoryDescription=document.querySelector('#category-description');
let SERVER_LEVELS=[],CATEGORIES=[],activeCategory=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function yt(u){const m=String(u||'').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{6,})/i);return m?m[1]:''}
function thumb(l){if(l.thumbnail_url)return l.thumbnail_url;if(l.thumbnail)return l.thumbnail;const id=yt(l.showcase_url||l.video);return id?'https://img.youtube.com/vi/'+id+'/hqdefault.jpg':''}
function normalize(l){return {...l,id:l.id,level_id:l.level_id||l.gd_id||'',video:l.showcase_url||l.video||'',thumbnail:l.thumbnail_url||l.thumbnail||''}}
async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});if(!r.ok)throw Error('Supabase '+r.status);return r.json()}
async function loadServer(){try{const [cats,levels]=await Promise.all([api('categories?select=*&order=position.asc'),api('levels?select=*&order=position.asc')]);CATEGORIES=cats||[];SERVER_LEVELS=(levels||[]).map(normalize);renderTabs();selectCategory(activeCategory||CATEGORIES[0]?.id||null);}catch(e){console.warn('Supabase indisponível',e);const fallback=Array.isArray(window.LEVELS)?window.LEVELS:[];SERVER_LEVELS=fallback;CATEGORIES=[{id:'fallback',name:'Main List',slug:'main-list',position:1}];renderTabs();selectCategory('fallback')}}
function renderTabs(){tabs.innerHTML=CATEGORIES.map(c=>'<button class="category-tab" data-category="'+esc(c.id)+'">'+esc(c.name)+'</button>').join('')+'<button class="category-tab players-tab" data-category="players">Melhores Jogadores</button>';tabs.querySelectorAll('.category-tab').forEach(b=>b.onclick=()=>selectCategory(b.dataset.category))}
function selectCategory(id){activeCategory=id;tabs.querySelectorAll('.category-tab').forEach(b=>b.classList.toggle('active',String(b.dataset.category)===String(id)));const players=id==='players';document.querySelector('#demon-category').hidden=players;document.querySelector('#players-category').hidden=!players;if(players){renderPlayers();return}const c=CATEGORIES.find(x=>String(x.id)===String(id));categoryTitle.textContent=c?.name||'Main List';categoryDescription.textContent=c?.description||'Os demons atualmente classificados nesta categoria.';render()}
function getLevels(){if(activeCategory==='fallback')return SERVER_LEVELS;if(activeCategory==null)return SERVER_LEVELS;return SERVER_LEVELS.filter(l=>String(l.category_id)===String(activeCategory))}
function closeDetails(){document.querySelector('#level-modal')?.remove()}
function showDetails(l){closeDetails();const id=yt(l.video),video=id?'<div class="video-wrap"><iframe src="https://www.youtube.com/embed/'+esc(id)+'" title="Showcase - '+esc(l.name)+'" allowfullscreen loading="lazy"></iframe></div>':'<div class="video-empty">Nenhum Showcase configurado.</div>',link=l.video?'<a class="showcase-link" href="'+esc(l.video)+'" target="_blank" rel="noopener">Abrir Showcase ↗</a>':'<span class="showcase-disabled">Showcase não configurado</span>',m=document.createElement('div');m.id='level-modal';m.className='modal-backdrop';m.innerHTML='<div class="level-modal"><button class="modal-close">×</button><div class="modal-rank">#'+esc(l.position)+'</div><h2>'+esc(l.name)+'</h2><p class="modal-creator">'+(l.creator?'por '+esc(l.creator):'Creator não definido')+'</p>'+video+'<div class="details-grid"><div><small>Dificuldade</small><strong>'+esc(l.difficulty||'Demon')+'</strong></div><div><small>Verificador</small><strong>'+esc(l.verifier||'Não definido')+'</strong></div><div><small>ID</small><strong>'+esc(l.level_id||'Não definido')+'</strong></div><div><small>Status</small><strong>'+esc(l.status||'Published')+'</strong></div></div><div class="showcase-area">'+link+'</div></div>';document.body.appendChild(m);m.querySelector('.modal-close').onclick=closeDetails;m.onclick=e=>{if(e.target===m)closeDetails()}}
function render(){const levels=getLevels(),q=(search.value||'').trim().toLowerCase(),items=levels.filter(l=>!q||[l.name,l.creator,l.verifier,l.level_id].join(' ').toLowerCase().includes(q)).sort((a,b)=>(+a.position||999999)-(+b.position||999999));count.textContent=levels.length;empty.hidden=items.length!==0;list.innerHTML=items.map(l=>'<article class="level">'+(thumb(l)?'<img class="level-thumb" src="'+esc(thumb(l))+'" alt="Thumbnail de '+esc(l.name)+'" loading="lazy">':'<div class="level-thumb placeholder">GD</div>')+'<div class="rank">#'+esc(l.position)+'</div><div class="level-info"><div class="name">'+esc(l.name)+'</div><div class="creator">'+(l.creator?'by '+esc(l.creator):'Creator not set')+'</div></div><div class="meta"><span class="difficulty">'+esc(l.difficulty||'Demon')+'</span><button class="view-btn" data-id="'+esc(l.id)+'">Ver 🔍</button></div></article>').join('');list.querySelectorAll('.view-btn').forEach(b=>b.onclick=()=>{const l=levels.find(x=>String(x.id)===String(b.dataset.id));if(l)showDetails(l)})}
async function renderPlayers(){const box=document.querySelector('#players-list');if(!box)return;try{const players=await api('players?select=*&order=points.desc,position.asc');box.innerHTML=players.map(p=>'<div class="player-row"><div class="player-rank">#'+esc(p.position)+'</div><div><strong>'+esc(p.name)+'</strong><small>'+esc(p.demons)+' demons · Hardest: '+esc(p.hardest)+'</small></div><b>'+esc(p.points)+' Points</b></div>').join('')||'<p class="empty">Nenhum jogador cadastrado.</p>';}catch(e){box.innerHTML='<p class="empty">Não foi possível carregar os jogadores.</p>'}}
search.addEventListener('input',render);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetails()});loadServer();