const list=document.querySelector('#list'),search=document.querySelector('#search'),count=document.querySelector('#count'),empty=document.querySelector('#empty');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function yt(u){const m=String(u||'').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{6,})/i);return m?m[1]:''}
function thumb(l){if(l.thumbnail)return l.thumbnail;const id=yt(l.video);return id?'https://img.youtube.com/vi/'+id+'/hqdefault.jpg':''}
function closeDetails(){document.querySelector('#level-modal')?.remove()}
function showDetails(l){closeDetails();const id=yt(l.video),video=id?'<div class="video-wrap"><iframe src="https://www.youtube.com/embed/'+esc(id)+'" title="Showcase - '+esc(l.name)+'" allowfullscreen loading="lazy"></iframe></div>':'<div class="video-empty">Nenhum Showcase configurado.</div>',link=l.video?'<a class="showcase-link" href="'+esc(l.video)+'" target="_blank" rel="noopener">Abrir Showcase ↗</a>':'<span class="showcase-disabled">Showcase não configurado</span>',m=document.createElement('div');m.id='level-modal';m.className='modal-backdrop';m.innerHTML='<div class="level-modal"><button class="modal-close">×</button><div class="modal-rank">#'+esc(l.position)+'</div><h2>'+esc(l.name)+'</h2><p class="modal-creator">'+(l.creator?'por '+esc(l.creator):'Creator não definido')+'</p>'+video+'<div class="details-grid"><div><small>Dificuldade</small><strong>'+esc(l.difficulty||'Demon')+'</strong></div><div><small>Verificador</small><strong>'+esc(l.verifier||'Não definido')+'</strong></div><div><small>ID</small><strong>'+esc(l.id||'Não definido')+'</strong></div><div><small>Status</small><strong>'+esc(l.status||'Published')+'</strong></div></div><div class="showcase-area">'+link+'</div></div>';document.body.appendChild(m);m.querySelector('.modal-close').onclick=closeDetails;m.onclick=e=>{if(e.target===m)closeDetails()}}
function render(){const levels=Array.isArray(window.LEVELS)?window.LEVELS:[],q=(search.value||'').trim().toLowerCase(),items=levels.filter(l=>!q||[l.name,l.creator,l.verifier,l.id].join(' ').toLowerCase().includes(q)).sort((a,b)=>(+a.position||999999)-(+b.position||999999));count.textContent=levels.length;empty.hidden=items.length!==0;list.innerHTML=items.map(l=>'<article class="level">'+(thumb(l)?'<img class="level-thumb" src="'+esc(thumb(l))+'" alt="Thumbnail de '+esc(l.name)+'" loading="lazy">':'<div class="level-thumb placeholder">GD</div>')+'<div class="rank">#'+esc(l.position)+'</div><div class="level-info"><div class="name">'+esc(l.name)+'</div><div class="creator">'+(l.creator?'by '+esc(l.creator):'Creator not set')+'</div></div><div class="meta"><span class="difficulty">'+esc(l.difficulty||'Demon')+'</span><button class="view-btn" data-position="'+esc(l.position)+'">Ver 🔍</button></div></article>').join('');list.querySelectorAll('.view-btn').forEach(b=>b.onclick=()=>{const l=levels.find(x=>String(x.position)===String(b.dataset.position));if(l)showDetails(l)})}
function renderPlayers(){const box=document.querySelector('#players-list');if(!box)return;const players=Array.isArray(window.PLAYERS)?window.PLAYERS:[];box.innerHTML=players.map(p=>'<div class="player-row"><div class="player-rank">#'+esc(p.position)+'</div><div><strong>'+esc(p.name)+'</strong><small>'+esc(p.demons)+' demons · Hardest: '+esc(p.hardest)+'</small></div><b>'+esc(p.points)+' CP</b></div>').join('')||'<p class="empty">Nenhum jogador cadastrado.</p>'}
function switchCategory(cat){document.querySelectorAll('.category-tab').forEach(b=>b.classList.toggle('active',b.dataset.category===cat));document.querySelector('#demon-category').hidden=cat!=='demons';document.querySelector('#players-category').hidden=cat!=='players';if(cat==='players')renderPlayers()}
search.addEventListener('input',render);document.querySelectorAll('.category-tab').forEach(b=>b.addEventListener('click',()=>switchCategory(b.dataset.category)));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetails()});render();renderPlayers();