const LEVELS = [
  { position: 1, name: "Silent uon", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 2, name: "abandoned", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 3, name: "silent Infernal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 4, name: "destino finaluon", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 5, name: "show your love v2", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 6, name: "insese", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 7, name: "infernal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 8, name: "brack blizzart", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 9, name: "saboorbawamba prev", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 10, name: "stereo extremeness", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 11, name: "Chaos Royal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 12, name: "Lightmare Royal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 13, name: "Nightmare Royal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 14, name: "Title Wave", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 15, name: "Royal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 16, name: "i can't see", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 17, name: "error 404", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 18, name: "stereo buffness", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 19, name: "SAB", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 20, name: "Chaos Royal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 21, name: "Lightmare Royal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 22, name: "Nightmare Royal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 23, name: "Title Wave", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 24, name: "Royal", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 25, name: "i can't see", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 26, name: "error 404", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 27, name: "stereo buffness", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 28, name: "SAB", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 29, name: "Fell in the sky", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 30, name: "blue nightmare", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 31, name: "SH1TTY", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" },
  { position: 32, name: "Clubstep do Silent", creator: "", id: null, verifier: "", difficulty: "Extreme Demon", video: "", status: "Published" }
];